### ISSUE TITLE
[container] apply layout and desing for main navigation using fexbox

### ISSUE THREAD

**Issue by snaphuman** [whiteflang/Project_Microfrontends_Mrcinema#2]
Ensure the following attributes:

* Navigation by keyboard
* Use semantic HTML
* Replicate styles and animation of the second "From Left" example of this demo: https://plantillashtmlgratis.com/wp-content/themes/helium-child/vista_previa/css/stylized-buttons/index.html

**Comment by whiteflang** [comment]
the design and layout for the main navigation using flexbox has been implemented and an animation has been added to the links.
